<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <NoStdLib>true</NoStdLib>
    <AssemblyName>SephiriaHiddenRoomHints</AssemblyName>
    <RootNamespace>SephiriaHiddenRoomHints</RootNamespace>
    <OutputPath>..\build\</OutputPath>
    <NoWarn>1701;1702</NoWarn>
    <SephiriaDir Condition="'$(SephiriaDir)' == ''">$(MSBuildProjectDirectory)\..\..\..\</SephiriaDir>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Presentation.cs" />
    <Compile Include="Plugin.cs" />
    <Reference Include="mscorlib">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\mscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\System.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\System.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(SephiriaDir)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\UnityEngine.GridModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(SephiriaDir)\Sephiria_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
